[[Libepoxy]]
arch = "aarch64"
git-tree-sha1 = "f377ed356ca83a1339adef1e24e3764cb20fa206"
os = "macos"

    [[Libepoxy.download]]
    sha256 = "0617030dfa5d914b724dab18ec88c6e4d8447f12994bbfa9855501b705b77bfd"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.aarch64-apple-darwin.tar.gz"
[[Libepoxy]]
arch = "aarch64"
git-tree-sha1 = "a2da8242ad09239c2f0bf8eb439b9f4354c5fcb7"
libc = "glibc"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "61c0e96649aab4db9effcec8dc2d79b5ab4ef9d9d47c0fe47768e0c31a2bb671"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.aarch64-linux-gnu.tar.gz"
[[Libepoxy]]
arch = "aarch64"
git-tree-sha1 = "139cb878c27402c5808f6676b2c6c9b9ca105e02"
libc = "musl"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "ab470764788223c47b080374698ad66ca7c9847a238beb44eff6b42d39f08200"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.aarch64-linux-musl.tar.gz"
[[Libepoxy]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9524e1717711ee72f7fc62a63f954735aaddb38b"
libc = "glibc"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "4df2479527515b753a922d65154ce858ae8a8a2c20f5fb6bca743fe2321f86d2"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.armv7l-linux-gnueabihf.tar.gz"
[[Libepoxy]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ba0cc6b233d42ccddb3443e716aaaa06f619f19"
libc = "musl"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "f9daeeb2305f1164f8875c570de90d941f75d04bb529b75338f39a93de623578"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.armv7l-linux-musleabihf.tar.gz"
[[Libepoxy]]
arch = "i686"
git-tree-sha1 = "05a15329a36feb80bd54b875f0dfbb744d9ed121"
libc = "glibc"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "69026abc906ce27fdcaada7291285414dca3651e80abbbf19b82ddc7e1c20a63"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.i686-linux-gnu.tar.gz"
[[Libepoxy]]
arch = "i686"
git-tree-sha1 = "490ca6d9ab762b0422e9e07c606bc6ad809d4894"
libc = "musl"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "81305953b7ad956ec4e5d7458976622bada146c7e31a694ecae6c1b53d9af7e8"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.i686-linux-musl.tar.gz"
[[Libepoxy]]
arch = "i686"
git-tree-sha1 = "0a98ddc58b57e7fb2cf15d43c4e3d1ab7353f8ab"
os = "windows"

    [[Libepoxy.download]]
    sha256 = "a4b1ec714589e6d4f9417c49574afa7bcbf60f3ff5435476ea81cd9d770d3938"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.i686-w64-mingw32.tar.gz"
[[Libepoxy]]
arch = "powerpc64le"
git-tree-sha1 = "73ec1e84c381d7fa6c801fa08aeba5f9d6229e03"
libc = "glibc"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "844a655c40f455a021083778fc9d5090c61158748c426015fa9e41dad6c1015b"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.powerpc64le-linux-gnu.tar.gz"
[[Libepoxy]]
arch = "x86_64"
git-tree-sha1 = "bfeb939eee1e3ae3f819d2cf90c85c3e239bbe5b"
os = "macos"

    [[Libepoxy.download]]
    sha256 = "26d1cd2ec7ba6db6b1414fcc0512a1cebd17160ee1154537af1409ceeab0d426"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.x86_64-apple-darwin.tar.gz"
[[Libepoxy]]
arch = "x86_64"
git-tree-sha1 = "0242d0c43707ea2700f2ac38bcf3577bb2c0fbbc"
libc = "glibc"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "383791d71d8ce69bc2b88898b5bd2692dd9ded2c45eb994fa7d884dd2de26609"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.x86_64-linux-gnu.tar.gz"
[[Libepoxy]]
arch = "x86_64"
git-tree-sha1 = "a99328d62deaf75ca997079680679787562775c9"
libc = "musl"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "a729e9b0ab442f2cecf6b51f24dd46041fb2fb036853d91a62893cf450ac3bb0"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.x86_64-linux-musl.tar.gz"
[[Libepoxy]]
arch = "x86_64"
git-tree-sha1 = "6fbdb3a02f6d7547944f0fdeb45195bdb18a5db7"
os = "freebsd"

    [[Libepoxy.download]]
    sha256 = "3ac9c0c6c5ffe436d619e41367c3e91c2be5cc3b4e14a8844683487a013524ef"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.x86_64-unknown-freebsd.tar.gz"
[[Libepoxy]]
arch = "x86_64"
git-tree-sha1 = "6ee48f4adeed324f32e71b70bf2fbce8f7b6685a"
os = "windows"

    [[Libepoxy.download]]
    sha256 = "a78e7bb8e680902e599822408f53a556d08ac1911933ec8493355761136c7c10"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.10+0/Libepoxy.v1.5.10.x86_64-w64-mingw32.tar.gz"
