[[Libepoxy]]
arch = "aarch64"
git-tree-sha1 = "dbbdc52fe84386a0f627f77a41c52c8e5e7ac267"
libc = "musl"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "4f580fff2adb2c6d11085225ffe065fa6b252deb08239db87a7226f1dd2dc0ea"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.aarch64-linux-musl.tar.gz"
[[Libepoxy]]
arch = "i686"
git-tree-sha1 = "a90700627355a8ab970fed1d6291e3e6539bb8e0"
os = "windows"

    [[Libepoxy.download]]
    sha256 = "0192f067963335a8a5b9c4ee2c1b33c8c5a8413e54ee6230d8c66c1be3023edc"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.i686-w64-mingw32.tar.gz"
[[Libepoxy]]
arch = "x86_64"
git-tree-sha1 = "2304fbc1a4c89887e06ba9ab94df2d87f8bed59e"
libc = "musl"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "10ca907a688d81c7cda1d1616d6ee11352479e428641587ea63b6b371cf05db4"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.x86_64-linux-musl.tar.gz"
[[Libepoxy]]
arch = "i686"
git-tree-sha1 = "b83d24ae42fbfcad132db94c2b138e59a8fe9d16"
libc = "glibc"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "5c5e43b8ea014e5c82760c90f6db671a9af535b812ff07a59c8aa09135793142"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.i686-linux-gnu.tar.gz"
[[Libepoxy]]
arch = "armv7l"
git-tree-sha1 = "e2c330ffc2d7b8bae70dec35c76ca457e347158c"
libc = "glibc"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "0194c67ef20f5039a426b512164cd77915c01af895af425f043ba25fec8b1dfc"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.armv7l-linux-gnueabihf.tar.gz"
[[Libepoxy]]
arch = "aarch64"
git-tree-sha1 = "168df5a6a8c22d3d18db1e346e4008c9351bbb59"
libc = "glibc"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "e0a3f7308d1534aa211d073d7ee170a40ae998dd39b6735df79347eaa9504110"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.aarch64-linux-gnu.tar.gz"
[[Libepoxy]]
arch = "x86_64"
git-tree-sha1 = "597c895c3922d0c91ae93d538514709b520b03e1"
libc = "glibc"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "2dc18273ae29c29d395fa5f737097ccd155cccbb5d526b77330dfe0d44904157"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.x86_64-linux-gnu.tar.gz"
[[Libepoxy]]
arch = "powerpc64le"
git-tree-sha1 = "a5786ae57a4f8d338f9090c0012ba226d4536dbc"
libc = "glibc"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "f06505e58e58aadccca92fcdfc4082a46493248b4cbebf0488c6722dca39e514"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.powerpc64le-linux-gnu.tar.gz"
[[Libepoxy]]
arch = "x86_64"
git-tree-sha1 = "598e138d78c045309b258d6a0e14ba17b8905e44"
os = "macos"

    [[Libepoxy.download]]
    sha256 = "b65c45ad0a598e9ab297b10cbf48b4c487e9546216606cae69dc854026cdb094"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.x86_64-apple-darwin14.tar.gz"
[[Libepoxy]]
arch = "x86_64"
git-tree-sha1 = "d4a0ffcd1b30a4926eb2cf18bd62349b2dfd8a25"
os = "freebsd"

    [[Libepoxy.download]]
    sha256 = "12aa05f11b84a8bd4d237b03c0c01db12c0559fd4bbb15dab93a7152e0bb5cec"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Libepoxy]]
arch = "i686"
git-tree-sha1 = "b4cce888debff3eb0715ee03cdb73b164ac33df6"
libc = "musl"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "71400c3445b38df6d1ed971caf097eda6e9ebe9a8a604db86bed2616a45eaaaa"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.i686-linux-musl.tar.gz"
[[Libepoxy]]
arch = "armv7l"
git-tree-sha1 = "6aa9fc0c5737e1a2b5e706ceaeba7e0edb0497f1"
libc = "musl"
os = "linux"

    [[Libepoxy.download]]
    sha256 = "4eaca08da8897248831d08e34edf1e4bc77f6bd175395e9940f3875a729f7af6"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.armv7l-linux-musleabihf.tar.gz"
[[Libepoxy]]
arch = "x86_64"
git-tree-sha1 = "34825b1cb6925c635dafc6ad3c2c3d161f48d609"
os = "windows"

    [[Libepoxy.download]]
    sha256 = "da4ecdc79caff7eaab85a91af6070a6722fd91cab24e2c9039e27189b58b4841"
    url = "https://github.com/JuliaBinaryWrappers/Libepoxy_jll.jl/releases/download/Libepoxy-v1.5.4+0/Libepoxy.v1.5.4.x86_64-w64-mingw32.tar.gz"
